### Create a new QTE Prompt
POST http://localhost:5000/qte-prompts
Content-Type: application/json

{
  "difficulty": 666,
  "timeLimit": 5,
  "points": 200
}

### Get all prompts (Use three hashtags to separate requests)
GET http://localhost:5000/qte-prompts

### filter prompts
GET http://localhost:5000/qte-prompts?key=SPACE&difficulty=hard

### Get user
GET http://localhost:5000/users/
Authorization: BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYzE1NzFkMWQwNzg4NmYzMDQyNjNiYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc5MTM0MTU4OSwiZXhwIjoxNzkxMzQ1MTg5fQ.dhEUrmMvm6r3mGNN2TbKGhS17y2PgX6tP75A4RoB_fk"


### Create Prompt
POST http://localhost:5000/qte-prompts/
Content-Type: application/json

{
    "key": "r"
}

### update prompt
PUT http://localhost:5000/qte-prompts/6abd51a357f67ec12d7d3e95
Content-Type: application/json

{
    "key": "W",
}

### create user
POST http://localhost:5000/users/
Content-Type: application/json

{
  "username": "Artoria",
  "email": "arethur2@gmail.com",
  "password": "asjfsda",
  "role": "admin"
}

### create game
POST http://localhost:5000/games/
Content-Type: application/json

{
  "userId": "6ac39d1208768a2ea71e748c",
  "mode": "singleplayer",
  "finalTime": 22.53,
  "wrongInputs": 3
}

### register user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "shuichi",
  "email": "shuichi@gmail.com",
  "password": "1234"
}

### login user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "monokuma",
  "email": "ono@gmail.com",
  "password": "1234"
}
